Update supervisord init scripts had lots of shellcheck issues

diff --git a/templates/supervisord.init-Debian.j2 b/templates/supervisord.init-Debian.j2
--- a/templates/supervisord.init-Debian.j2
+++ b/templates/supervisord.init-Debian.j2
@@ -25,114 +25,113 @@
 #                    subprocesses.
 ### END INIT INFO
 
+# shellcheck source=/dev/null
 . /lib/lsb/init-functions
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON={{ supervisor_bin_path }}
+DAEMON="{{ supervisor_bin_path }}"
 SUPERVISORCTL=/usr/bin/supervisorctl
 NAME=supervisord
 DESC=supervisor
 
-test -x $DAEMON || exit 0
+test -x "$DAEMON" || exit 0
 
-LOGDIR=/var/log/supervisor
+export LOGDIR=/var/log/supervisor
 PIDFILE=/var/run/$NAME.pid
-DODTIME=5                   # Time to wait for the server to die, in seconds
-                            # If this value is set too low you might not
-                            # let some servers to die gracefully and
-                            # 'restart' will not work
+DODTIME=5 # Time to wait for the server to die, in seconds
+# If this value is set too low you might not
+# let some servers to die gracefully and
+# 'restart' will not work
 
 # Include supervisor defaults if available
-if [ -f /etc/default/supervisor ] ; then
+if [ -f /etc/default/supervisor ]; then
   . /etc/default/supervisor
 fi
 DAEMON_OPTS="-c {{ supervisor_config_path }}/supervisord.conf $DAEMON_OPTS"
 
 set -e
 
-running_pid()
-{
-    # Check if a given process pid's cmdline matches a given name
-    pid=$1
-    name=$2
-    [ -z "$pid" ] && return 1
-    [ ! -d /proc/$pid ] &&  return 1
-    (cat /proc/$pid/cmdline | tr "\000" "\n"|grep -q $name) || return 1
-    return 0
+running_pid() {
+  # Check if a given process pid's cmdline matches a given name
+  pid=$1
+  name=$2
+  [ -z "$pid" ] && return 1
+  [ ! -d /proc/"$pid" ] && return 1
+  (tr "\000" "\n" < "/proc/$pid/cmdline" | grep -q "$name") || return 1
+  return 0
 }
 
-running()
-{
-# Check if the process is running looking at /proc
-# (works for all users)
+running() {
+  # Check if the process is running looking at /proc
+  # (works for all users)
 
-    # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILE" ] && return 1
-    # Obtain the pid and check it against the binary name
-    pid=`cat $PIDFILE`
-    running_pid $pid $DAEMON || return 1
-    return 0
+  # No pidfile, probably no daemon present
+  [ ! -f "$PIDFILE" ] && return 1
+  # Obtain the pid and check it against the binary name
+  pid=$(cat $PIDFILE)
+  running_pid "$pid" "$DAEMON" || return 1
+  return 0
 }
 
 force_stop() {
-# Forcefully kill the process
-    [ ! -f "$PIDFILE" ] && return
-    if running ; then
-        kill -15 $pid
-        # Is it really dead?
-        [ -n "$DODTIME" ] && sleep "$DODTIME"s
-        if running ; then
-            kill -9 $pid
-            [ -n "$DODTIME" ] && sleep "$DODTIME"s
-            if running ; then
-                echo "Cannot kill $NAME (pid=$pid)!"
-                exit 1
-            fi
-        fi
+  # Forcefully kill the process
+  [ ! -f "$PIDFILE" ] && return
+  if running; then
+    kill -15 "$pid"
+    # Is it really dead?
+    [ -n "$DODTIME" ] && sleep "$DODTIME"s
+    if running; then
+      kill -9 "$pid"
+      [ -n "$DODTIME" ] && sleep "$DODTIME"s
+      if running; then
+        echo "Cannot kill $NAME (pid=$pid)!"
+        exit 1
+      fi
     fi
-    rm -f $PIDFILE
-    return 0
+  fi
+  rm -f $PIDFILE
+  return 0
 }
 
 case "$1" in
-  start)
-  echo -n "Starting $DESC: "
+start)
+  printf "Starting %s: " "$DESC"
   start-stop-daemon --start --quiet --pidfile $PIDFILE \
-    --startas $DAEMON -- $DAEMON_OPTS
+    --startas "$DAEMON" -- "$DAEMON_OPTS"
   test -f $PIDFILE || sleep 1
-        if running ; then
-            echo "$NAME."
-        else
-            echo " ERROR."
-        fi
+  if running; then
+    echo "$NAME."
+  else
+    echo " ERROR."
+  fi
   ;;
-  stop)
-  echo -n "Stopping $DESC: "
+stop)
+  printf "Stopping %s: " "$DESC"
   start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
   echo "$NAME."
   ;;
-  force-stop)
-  echo -n "Forcefully stopping $DESC: "
-        force_stop
-        if ! running ; then
-            echo "$NAME."
-        else
-            echo " ERROR."
-        fi
+force-stop)
+  printf "Forcefully stopping %s: " "$DESC"
+  force_stop
+  if ! running; then
+    echo "$NAME."
+  else
+    echo " ERROR."
+  fi
   ;;
-  #reload)
-  #
-  # If the daemon can reload its config files on the fly
-  # for example by sending it SIGHUP, do it here.
-  #
-  # If the daemon responds to changes in its config file
-  # directly anyway, make this a do-nothing entry.
-  #
-  # echo "Reloading $DESC configuration files."
-  # start-stop-daemon --stop --signal 1 --quiet --pidfile \
-  # /var/run/$NAME.pid --exec $DAEMON
-  #;;
-  force-reload)
+#reload)
+#
+# If the daemon can reload its config files on the fly
+# for example by sending it SIGHUP, do it here.
+#
+# If the daemon responds to changes in its config file
+# directly anyway, make this a do-nothing entry.
+#
+# echo "Reloading $DESC configuration files."
+# start-stop-daemon --stop --signal 1 --quiet --pidfile \
+# /var/run/$NAME.pid --exec $DAEMON
+#;;
+force-reload)
   #
   # If the "reload" option is implemented, move the "force-reload"
   # option to the "reload" entry above. If not, "force-reload" is
@@ -140,29 +139,29 @@ case "$1" in
   #   daemon isn't already running.
   # check wether $DAEMON is running. If so, restart
   start-stop-daemon --stop --test --quiet --pidfile $PIDFILE \
-        --startas $DAEMON \
-  && $0 restart \
-  || exit 0
+    --startas "$DAEMON" &&
+    $0 restart ||
+    exit 0
   ;;
-  restart)
-    echo -n "Restarting $DESC: "
-    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
+restart)
+  printf "Restarting %s: " "$DESC"
+  start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
   [ -n "$DODTIME" ] && sleep $DODTIME
   start-stop-daemon --start --quiet --pidfile $PIDFILE \
-    --startas $DAEMON -- $DAEMON_OPTS
+    --startas "$DAEMON" -- "$DAEMON_OPTS"
   echo "$NAME."
   ;;
-  status)
-    echo -n "$NAME is "
-    if running ;  then
-        echo "running"
-    else
-        echo " not running."
-        exit 1
-    fi
-    $SUPERVISORCTL $DAEMON_OPTS status
-    ;;
-  *)
+status)
+  printf "%s is " "$NAME"
+  if running; then
+    echo "running"
+  else
+    echo " not running."
+    exit 1
+  fi
+  $SUPERVISORCTL "$DAEMON_OPTS" status
+  ;;
+*)
   N=/etc/init.d/$NAME
   # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
   echo "Usage: $N {start|stop|restart|force-reload|status|force-stop}" >&2
